apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.application_id}}
  description: ${{values.description}}
  labels:
    size: ${{values.size}}
    environments: ${{values.environments.replaceAll(',','-')}}
spec:
  owner: ${{values.owner}}