site_name: ios-pwa-app
site_description: "A Progressive Web App (PWA) is a type of web app that can be installed on a device as a standalone application."
repo_url: https://github.com/99x/product-central-architectures/tree/main/architectures/docs/techdocs/ios-pwa-app
edit_uri: edit/main/docs/techdocs/ios-pwa-app

plugins:
  - techdocs-core

nav:
  - Application Architecture: index.md
  - Design Philosophy:
      - Introduction: design-philosophy/introduction.md
      - Front End Architecture: design-philosophy/front-end-architecture.md
      - BFF Architecture: design-philosophy/bff-architecture.md
      - Repository Strategy:
          - Organization of the source repository: design-philosophy/organization-of-the-source-repository.md
          - Folder Structure: design-philosophy/folder-structure.md
