name: Client CI
on:
  pull_request:
    paths:
      - "client/**"
    # TODO: add restrictions (Branch Protection Rule) to only allow pushes to this branch from PRs
    branches:
      - development
      - staging
      - production
      - release

permissions:
  actions: read
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn-cache
            ./client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

  build:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn-cache
            ./client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Derive approriate SHAs for base and head for nx affected
        uses: nrwl/nx-set-shas@v4

      # affected uses git to determine the files we changed, and execute only that are affected by the changes
      # only used upon making a PR
      - name: Build Affected Apps
        env:
          NEXT_PRIVATE_LOCAL_WEBPACK: true
        run: |
          yarn affected:build

  affected:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn-cache
            ./client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check for lint errors
        run: yarn affected:lint

      - name: Test affected apps
        run: yarn affected:test
