apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: ${{ values.name | dump }}
    annotations:
        github.com/project-slug: ${{ values.slug }}
        backstage.io/techdocs-ref: ${{ values.slug }}
    description: ${{ values.name }} is a micro-frontend application which is built using Next.js and served using Module Federation and NX tool deployed in AWS.
    tags:
        - aws
        - nextjs
        - micro-frontend
        - nx
        - module-federation
    links:
      - url: https://github.com/99x/product-central-architectures
        title: 99x Product Central Architectures
        icon: dashboard
spec:
    type: service
    owner: user:99xadmin
    lifecycle: production
    system: productcentral
