# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RA_APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RA_APP
  #Pods for Alamofire
  pod "Alamofire"
  
  #Pods for RxSwift
  pod “RxSwift”
  pod “RxCocoa”

  target 'RA_APPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RA_APPUITests' do
    # Pods for testing
  end

end
