apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: ${{ values.slug }}
     backstage.io/adr-location: https://github.com/99x/product-central-architectures/tree/development/architectures/docs/decisions/architectures/github/ios-api-client-app
    backstage.io/techdocs-ref: url:https://github.com/99x/product-central-architectures/tree/development/architectures/docs/techdocs/architectures/github/ios-api-client-app
 description: ${{ values.name }} is a iOS Application With Networking Libraries including Alamofire framework along with RxSwift. This includes the basic API call structure. Developers can install the libraries via pods.
     tags:
    - native-ios
    - networking-library
    - xcode
    - ios-swift
    - alamofire
    - rx-swift
    - ios-swift
    - reference-architecture
  links:
    - url: https://github.com/99x/product-central-architectures
      title: 99x Product Central Architectures
      icon: dashboard
spec:
  type: service
  owner: user:99xadmin
  lifecycle: production
  system: productcentral
