title: Product Central Architectures
description: Collection of Software Architectures / Golden Path for Product Central buckets bundled with TechDocs and ADR.
theme: just-the-docs

logo: /assets/img/product-central-logo-light.svg
favicon_ico: /assets/img/product-central-icon-light.svg

url: https://99x.github.io/product-central-architectures

aux_links:
  Template Repository: https://github.com/99x/product-central-architectures

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

mermaid:
  version: "9.1.3"

nav_enabled: true

heading_anchors: true

color_scheme: light

