apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: obc-template
  title: Add OBC to an existing project
  description: Add OBC to an existing project
  tags:
    - obc
spec:
  owner: user:99xadmin
  system: ProductCentral
  type: service

  parameters:
    - title: Provide information about the existing component
      required:
        - orgName
        - repoName
      properties:
        orgName:
          title: Organization Name
          type: string
        repoName:
          title: Repository Name
          type: string
    - title: Provide information about the new component
      required:
        - owner
        - system
        - storageClassName
      properties:
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        storageClassName:
          title: Storage Class Name
          type: string
          description: Storage Class Name of the OBC
  steps:
    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        values:
          # Gitops specific values
          entityKind: Resource

          # Normal values
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the OBC manifests for ${{ parameters.repoName }}
          sourceControl: github.com

    - id: manifestsTemplate
      name: Generating the Manifests Component
      action: fetch:template
      input:
        url: ./template
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the OBC manifests for ${{ parameters.repoName }}
          sourceControl: github.com

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}-gitops
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
